spring:
  kafka:
    bootstrap-servers: # {host}:{port}
    consumer:
      group-id: # {Consumer Group Name}
    template:
      default-topic: # {Topic Name}
  redis:
    host: # {host}
    port: # {port}